function [headers] = getSDFheaders()
%% All headers names
headers.name = {'version', ...
                'ManufacID', ...
                'CreateDate', 'ModDate', ...
                'NumPoints', ... 
                'NumProfiles', ...
                'Xscale', 'Yscale', 'Zscale', 'Zresolution', ...
                'Compression', 'DataType', 'CheckType'};
       
%% Headers infos
headers.infos.version = struct( ...
                    'bytes', 8, ...
                    'precision', 'uchar', ...
                    'output', 'char');
                
headers.infos.ManufacID = struct( ...
                    'bytes', 10, ...
                    'precision', 'uchar', ...
                    'output', 'char');
                
headers.infos.CreateDate = struct( ...
                    'bytes', 12, ...
                    'precision', 'uchar', ...
                    'output', 'double');
                
headers.infos.ModDate = struct( ...
                    'bytes', 12, ...
                    'precision', 'uchar', ...
                    'output', 'double');

headers.infos.NumPoints = struct( ...
                    'bytes', 1, ...
                    'precision', 'uint16', ...
                    'output', 'double');
                
headers.infos.NumProfiles = struct( ...
                    'bytes', 1, ...
                    'precision', 'uint16', ...
                    'output', 'double');
                
headers.infos.Xscale = struct( ...
                    'bytes', 1, ...
                    'precision', 'double', ...
                    'output', 'double');
                
headers.infos.Yscale = struct( ...
                    'bytes', 1, ...
                    'precision', 'double', ...
                    'output', 'double');
                
headers.infos.Zscale = struct( ...
                    'bytes', 1, ...
                    'precision', 'double', ...
                    'output', 'double');
                
headers.infos.Zresolution = struct( ...
                    'bytes', 1, ...
                    'precision', 'double', ...
                    'output', 'double');
                
headers.infos.Compression = struct( ...
                    'bytes', 1, ...
                    'precision', 'uchar', ...
                    'output', 'double');
                
headers.infos.DataType = struct( ...
                    'bytes', 1, ...
                    'precision', 'uchar', ...
                    'output', 'double');
                
headers.infos.CheckType = struct( ...
                    'bytes', 1, ...
                    'precision', 'uchar', ...
                    'output', 'double');
end
